import React, { useState } from 'react';
import { ClipboardPlus, MessageSquareHeart } from 'lucide-react';
import type { CaregiverObservation } from '../../types';
import { api } from '../../services/api';

interface ObservationsPanelProps { patientId: string; observations: CaregiverObservation[]; onAdded: (observation: CaregiverObservation) => void }
const availableTags = ['sleep', 'illness', 'mood', 'medication', 'routine', 'other'];
export const ObservationsPanel: React.FC<ObservationsPanelProps> = ({ patientId, observations, onAdded }) => {
  const [note, setNote] = useState(''); const [tags, setTags] = useState<string[]>([]); const [saving, setSaving] = useState(false); const [error, setError] = useState('');
  const submit = async (event: React.FormEvent) => { event.preventDefault(); if (!note.trim()) return; setSaving(true); setError(''); try { const result = await api.addObservation(patientId, { note, tags }); onAdded(result.observation); setNote(''); setTags([]); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Unable to save observation.'); } finally { setSaving(false); } };
  return <div className="grid gap-5 lg:grid-cols-[.8fr_1.2fr]"><form onSubmit={submit} className="rounded-3xl border border-stone-200 bg-white p-5 shadow-sm"><div className="flex items-center gap-3"><ClipboardPlus className="h-7 w-7 text-brahma-700" /><div><h2 className="text-xl font-black">Add caregiver observation</h2><p className="text-sm font-semibold text-stone-500">Record context, not a diagnosis.</p></div></div><label className="mt-5 block"><span className="mb-2 block font-bold">What did you notice?</span><textarea value={note} onChange={(event) => setNote(event.target.value)} required className="min-h-36 w-full rounded-2xl border-2 border-stone-200 p-3 outline-none focus:border-brahma-600" placeholder="Example: Slept poorly and needed two extra reminders this morning." /></label><fieldset className="mt-4"><legend className="font-bold">Context tags</legend><div className="mt-2 flex flex-wrap gap-2">{availableTags.map((tag) => <button key={tag} type="button" onClick={() => setTags((values) => values.includes(tag) ? values.filter((item) => item !== tag) : [...values, tag])} className={`min-h-10 rounded-full border px-3 text-sm font-black capitalize ${tags.includes(tag) ? 'border-brahma-700 bg-brahma-600 text-white' : 'border-stone-300 bg-stone-100'}`} aria-pressed={tags.includes(tag)}>{tag}</button>)}</div></fieldset>{error && <p className="mt-3 rounded-xl bg-rose-50 p-3 font-bold text-rose-800">{error}</p>}<button disabled={saving} className="mt-5 min-h-12 w-full rounded-xl bg-brahma-700 font-black text-white">{saving ? 'Saving…' : 'Save observation'}</button></form><section className="rounded-3xl border border-stone-200 bg-white p-5 shadow-sm"><div className="flex items-center gap-3"><MessageSquareHeart className="h-7 w-7 text-tea-700" /><h2 className="text-xl font-black">Observation timeline</h2></div><div className="mt-5 space-y-3">{observations.length ? observations.map((observation) => <article key={observation.id} className="rounded-2xl border border-stone-200 bg-stone-50 p-4"><div className="flex flex-wrap items-center justify-between gap-2"><span className="font-black text-stone-900">{observation.caregiverName}</span><time className="text-sm font-semibold text-stone-500">{new Date(observation.observedAt).toLocaleString('en-IN', { dateStyle: 'medium', timeStyle: 'short' })}</time></div><p className="mt-2 font-semibold leading-relaxed text-stone-700">{observation.note}</p><div className="mt-3 flex flex-wrap gap-2">{observation.tags.map((tag) => <span key={tag} className="rounded-full bg-white px-2.5 py-1 text-xs font-black capitalize text-brahma-800">{tag}</span>)}</div></article>) : <p className="rounded-2xl bg-stone-50 p-6 text-center font-semibold text-stone-500">No observations yet. Context can make activity trends easier to interpret.</p>}</div></section></div>;
};
